name: hello_rabbitmq

services:

  order_db:
    image: postgres:18
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "order_db"]
    volumes:
      - pgdata:/var/lib/postgresql

  rabbitmq:
    image: rabbitmq:4.3.2-management
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq

  order_service:
    image: order_service
    build:
      context: .
      dockerfile: src/OrderService/Dockerfile
    depends_on:
      order_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - 5000:8080
    environment:
      ASPNETCORE_URLS: "http://+8080"
      ConnectionStrings__DefaultConnection: "Host=order_db;Port=5432;Database=order_db;Username=postgres;Password=root"
      RabbitMq__HostName: "rabbitmq"
      
  payment_service:
    image: payment_service
    build:
      context: .
      dockerfile: src/PaymentService/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - 5001:8080
    environment:
      ASPNETCORE_URLS: "http://+8080"
      RabbitMq__HostName: "rabbitmq"

  notification_service:
    image: notification_service
    build:
      dockerfile: src/NotificationService/Dockerfile
      context: .
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - 5083:8080
    environment:
      ASPNETCORE_URLS: "http://+8080"
      RabbitMq__HostName: "rabbitmq"

volumes:
  pgdata:
    name: hello_rabbitmq_pgdata
  rabbitmqdata:
    name: hello_rabbitmq_rabbitmqdata
